export { default as Burger } from './Burger'
export { default as Close } from './Close'
export { default as FoodServing } from './FoodServing'
export { default as ShoppingCart } from './ShoppingCart'
export { default as TakeAway } from './TakeAway'